#! /bin/sh
#Mouse config 
xinput set-prop 'ELAN0718:00 04F3:30FD Touchpad' 'libinput Tapping Enabled' 1
xinput set-prop 'ELAN0718:00 04F3:30FD Touchpad' 'libinput Natural Scrolling Enabled'>
xsetroot -cursor_name left_ptr

#Keyboard
numlockx on

#This prevents weird behavior when switching to nvidia graphics (my hardware) 
xrandr --auto
bspc monitor -g 1920x1080+0+0
xrandr --output eDP --set TearFree on && dunstify sucess

#general config
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width                  3
bspc config window_gap                    10
bspc config single_monocle                true
bspc config split_ratio                   0.52
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config top_padding                   30
bspc config focus_follows_pointer         true
bspc config bocused_border_color         "#83a598"

#Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a gnome-calcutator state=floating

#Wallpaper, bar, and compositor
feh --bg-scale /home/$USER/<path-to>/collanimegirl.png
killall polybar
polybar -c ~/.config/polybar/config bar1 &
killall compton
compton -c 
