#! /bin/sh

#Mouse config 
xinput set-prop 'ELAN0718:00 04F3:30FD Touchpad' 338 1
xinput set-prop 'ELAN0718:00 04F3:30FD Touchpad' 320 1
xsetroot -cursor_name left_ptr

#Keyboard config
numlockx on

#General config
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width        	  3
bspc config window_gap          	  8
bspc config single_monocle  	  	  true
bspc config split_ratio          	  0.52
bspc config borderless_monocle    	  false
bspc config gapless_monocle     	  false
bspc config top_padding 		  30
bspc config focus_follows_pointer	  true
bspc config bocused_border_color	 "#83a598"

#Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Wallpaper, bar, and compositor
feh --bg-scale <path-to-image>/collanimegirl.png
killall polybar
polybar -c ~/.config/polybar/config bar1 &
killall compton
compton -c 

#bad fix for my screentear but works 
xrandr --output eDP --set TearFree on

#scripts
<path-to-script>/.batery-low.sh 

